[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/about"
  to = "/mission"
  status = 301

[[redirects]]
  from = "/lenders-digest"
  to = "/insights"
  status = 301

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200



